/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as PeopleRouteImport } from './routes/people'
import { Route as BBoardIdRouteImport } from './routes/b.$boardId'
import { Route as BBoardIdIndexRouteImport } from './routes/b.$boardId.index'
import { Route as BBoardIdGanttRouteImport } from './routes/b.$boardId.gantt'
import { Route as BBoardIdReportRouteImport } from './routes/b.$boardId.report'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const PeopleRoute = PeopleRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => rootRouteImport,
} as any)
const BBoardIdRoute = BBoardIdRouteImport.update({
  id: '/b/$boardId',
  path: '/b/$boardId',
  getParentRoute: () => rootRouteImport,
} as any)
const BBoardIdIndexRoute = BBoardIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BBoardIdRoute,
} as any)
const BBoardIdGanttRoute = BBoardIdGanttRouteImport.update({
  id: '/gantt',
  path: '/gantt',
  getParentRoute: () => BBoardIdRoute,
} as any)
const BBoardIdReportRoute = BBoardIdReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => BBoardIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/people': typeof PeopleRoute
  '/b/$boardId': typeof BBoardIdRouteWithChildren
  '/b/$boardId/gantt': typeof BBoardIdGanttRoute
  '/b/$boardId/report': typeof BBoardIdReportRoute
  '/b/$boardId/': typeof BBoardIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/people': typeof PeopleRoute
  '/b/$boardId/gantt': typeof BBoardIdGanttRoute
  '/b/$boardId/report': typeof BBoardIdReportRoute
  '/b/$boardId': typeof BBoardIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/people': typeof PeopleRoute
  '/b/$boardId': typeof BBoardIdRouteWithChildren
  '/b/$boardId/gantt': typeof BBoardIdGanttRoute
  '/b/$boardId/report': typeof BBoardIdReportRoute
  '/b/$boardId/': typeof BBoardIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/messages'
    | '/people'
    | '/b/$boardId'
    | '/b/$boardId/gantt'
    | '/b/$boardId/report'
    | '/b/$boardId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/login'
    | '/messages'
    | '/people'
    | '/b/$boardId/gantt'
    | '/b/$boardId/report'
    | '/b/$boardId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/login'
    | '/messages'
    | '/people'
    | '/b/$boardId'
    | '/b/$boardId/gantt'
    | '/b/$boardId/report'
    | '/b/$boardId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  LoginRoute: typeof LoginRoute
  MessagesRoute: typeof MessagesRoute
  PeopleRoute: typeof PeopleRoute
  BBoardIdRoute: typeof BBoardIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/people': {
      id: '/people'
      path: '/people'
      fullPath: '/people'
      preLoaderRoute: typeof PeopleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/b/$boardId': {
      id: '/b/$boardId'
      path: '/b/$boardId'
      fullPath: '/b/$boardId'
      preLoaderRoute: typeof BBoardIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/b/$boardId/': {
      id: '/b/$boardId/'
      path: '/'
      fullPath: '/b/$boardId/'
      preLoaderRoute: typeof BBoardIdIndexRouteImport
      parentRoute: typeof BBoardIdRoute
    }
    '/b/$boardId/gantt': {
      id: '/b/$boardId/gantt'
      path: '/gantt'
      fullPath: '/b/$boardId/gantt'
      preLoaderRoute: typeof BBoardIdGanttRouteImport
      parentRoute: typeof BBoardIdRoute
    }
    '/b/$boardId/report': {
      id: '/b/$boardId/report'
      path: '/report'
      fullPath: '/b/$boardId/report'
      preLoaderRoute: typeof BBoardIdReportRouteImport
      parentRoute: typeof BBoardIdRoute
    }
  }
}

interface BBoardIdRouteChildren {
  BBoardIdGanttRoute: typeof BBoardIdGanttRoute
  BBoardIdReportRoute: typeof BBoardIdReportRoute
  BBoardIdIndexRoute: typeof BBoardIdIndexRoute
}

const BBoardIdRouteChildren: BBoardIdRouteChildren = {
  BBoardIdGanttRoute: BBoardIdGanttRoute,
  BBoardIdReportRoute: BBoardIdReportRoute,
  BBoardIdIndexRoute: BBoardIdIndexRoute,
}

const BBoardIdRouteWithChildren = BBoardIdRoute._addFileChildren(
  BBoardIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  LoginRoute: LoginRoute,
  MessagesRoute: MessagesRoute,
  PeopleRoute: PeopleRoute,
  BBoardIdRoute: BBoardIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
